CREATE TABLE IF NOT EXISTS icehive_meta (
    k VARCHAR(255) NOT NULL PRIMARY KEY,
    v TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS icehive_heartbeats (
    service_name VARCHAR(255) NOT NULL PRIMARY KEY,
    latest_heartbeat_unix_ms BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
